### ISSUE TITLE
fails with latest cutorch/cunn

### ISSUE THREAD

**Issue by soumith** [nicholas-leonard/cunnx#22]
As reported by several people. can you fix?

[100%] Building NVCC (Device) object CMakeFiles/cunnx.dir//./cunnx_generated_init.cu.o
/gpuusers/ms/cs15s023/cunnx-master/SoftMaxTree.cu(439): error: argument of type "THCudaTensor *" is incompatible with parameter of type "THCudaIntTensor *"

/gpuusers/ms/cs15s023/cunnx-master/BlockSparse.cu(99): error: argument of type "THCudaTensor *" is incompatible with parameter of type "THCudaLongTensor *"

/gpuusers/ms/cs15s023/cunnx-master/BlockSparse.cu(100): error: argument of type "THCudaTensor *" is incompatible with parameter of type "THCudaLongTensor *"

/gpuusers/ms/cs15s023/cunnx-master/WindowGate.cu(110): error: argument of type "THCudaTensor *" is incompatible with parameter of type "THCudaLongTensor *"

/gpuusers/ms/cs15s023/cunnx-master/WindowGate2.cu(120): error: argument of type "THCudaTensor *" is incompatible with parameter of type "THCudaLongTensor *"

5 errors detected in the compilation of "/tmp/tmpxft_000042aa_00000000-7_init.cpp1.ii".
CMake Error at cunnx_generated_init.cu.o.cmake:262 (message):
  Error generating file
  /gpuusers/ms/cs15s023/cunnx-master/CMakeFiles/cunnx.dir//./cunnx_generated_init.cu.o

make[2]: *** [CMakeFiles/cunnx.dir/./cunnx_generated_init.cu.o] Error 1
make[1]: *** [CMakeFiles/cunnx.dir/all] Error 2
make: *** [all] Error 2

**Comment by nicholas-leonard** [comment]
@soumith Arggg, stop changing things! Working on it :)

**Comment by nicholas-leonard** [comment]
fixed for SoftMaxTree. Thanks for help guys.
