### ISSUE TITLE
Error with BlockSpare

### ISSUE THREAD

**Issue by nn-learner** [nicholas-leonard/cunnx#32]
Hi,

I was wondering if this library was still being maintained. I tried install cunnx through luarocks but am facing the following issue:

/tmp/luarocks_cunnx-scm-1-1376/cunnx/BlockSparse.cu(511): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_0000667c_00000000-7_init.cpp1.ii".
CMake Error at cunnx_generated_init.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cunnx-scm-1-1376/cunnx/build/CMakeFiles/cunnx.dir//./cunnx_generated_init.cu.o

If you had any suggestions, that would be much appreciated.

**Comment by 1p1pd** [comment]
me too

**Comment by rohitgajawada** [comment]
I got the same error :( 
/tmp/luarocks_cunnx-scm-1-614/cunnx/BlockSparse.cu(511): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00006e31_00000000-7_init.cpp1.ii".
CMake Error at cunnx_generated_init.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cunnx-scm-1-614/cunnx/build/CMakeFiles/cunnx.dir//./cunnx_generated_init.cu.o


CMakeFiles/cunnx.dir/build.make:63: recipe for target 'CMakeFiles/cunnx.dir/cunnx_generated_init.cu.o' failed
make[2]: *** [CMakeFiles/cunnx.dir/cunnx_generated_init.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cunnx.dir/all' failed
make[1]: *** [CMakeFiles/cunnx.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by 1p1pd** [comment]
I changed that line 511 to
`THCudaTensor_sum(state, gradInput, gradInputBatched, 0, 1);`

**Comment by phuongnm-bkhn** [comment]
me too @@ any idea ?

**Comment by phuongnm-bkhn** [comment]
@1p1pd   why?, this is bug or ?

**Comment by nicholas-leonard** [comment]
https://github.com/nicholas-leonard/cunnx/commit/3307c4a1f857bdd967a8813b732cf6a1789d1dbe
